### ISSUE TITLE
Anti-Gravity Arrow

### ISSUE THREAD

**Issue by KyleMcLainKane** [AztecGameLab/LongTermGame4#129]
Hit collision
Ambient sound for objects with flipped gravity
Physical objects

**Comment by rynls** [comment]
Anti-gravity magic SFX after an arrow collision + going into ambient flipped gravity noise:
https://drive.google.com/file/d/1v-tYFCT3Vgcpe0zykqQVyD3JKXv7MxW5/view?usp=sharing

Flipped gravity noise loop:
https://drive.google.com/file/d/1qVihfJn31XILBuh8yw6PCtaV9gevLTGf/view?usp=sharing

Magic SFX after arrow collision to flip back to normal gravity:
https://drive.google.com/file/d/1a993h3j1APFiRkW-J-_SceBrpYQkPR2y/view?usp=sharing 

Anti-gravity SFX full cycle (start and stop), ~30 sec.:
https://drive.google.com/file/d/1Hij1v_r_zvAVA9jKsYdKC5NjXlG8xW3e/view?usp=sharing 


**Question: Github says .wav files aren't supported, so I tried links to the Audio Google Drive folder. Should I do something different?

**Comment by KyleMcLainKane** [comment]
Could you post a screenshot of the whole issue with uploading to gibhub? Or feel free to dm it to me

**Comment by rynls** [comment]
![image](https://user-images.githubusercontent.com/72280792/97509671-2b4d0000-1940-11eb-8df0-f2b74544ebd8.png)

**Comment by KyleMcLainKane** [comment]
Ah I see what your trying to do. So this write section is meant for reviews and comments on your code/product. Take a look at this PDF I have attached to this comment, and if your having issues accessing it, it is also pinned in the #ltg channel on discord.
[Github_instructions (3).pdf](https://github.com/AztecGameLab/LongTermGame4/files/5455519/Github_instructions.3.pdf)

**Comment by KyleMcLainKane** [comment]
Forgot to mention, do not hesitate to dm me or any of the other admins if you need help with this.

**Comment by rynls** [comment]
Thanks! I'll take a look at that.
