### ISSUE TITLE
Bow Concept Art

### ISSUE THREAD

**Issue by KyleMcLainKane** [AztecGameLab/LongTermGame4#14]
Come up with bow silhouette, arrow design, colors, accents etc etc

**Comment by NaseemTahbaz** [comment]
![BOW-AND-ARROW-SILHOUETTES-NASEEM-TAHBAZ](https://user-images.githubusercontent.com/49079412/95550124-3ce45d00-09bd-11eb-9d25-fa46f08b16a0.png)
![BOW-AND-ARROW-COLOR-SCHEME-1](https://user-images.githubusercontent.com/49079412/95550127-3d7cf380-09bd-11eb-86bf-223ae1422c39.png)
![BOW-AND-ARROW-COLOR-SCHEME-1-ACCENTS](https://user-images.githubusercontent.com/49079412/95550129-3eae2080-09bd-11eb-9190-2a272b26e985.png)
![BOW-AND-ARROW-COLOR-SCHEME-2](https://user-images.githubusercontent.com/49079412/95550131-3eae2080-09bd-11eb-8045-4a2952a97b96.png)
![BOW-AND-ARROW-COLOR-SCHEME-3](https://user-images.githubusercontent.com/49079412/95550132-3f46b700-09bd-11eb-8358-8fc89bd96a4f.png)
![BOW-AND-ARROW-COLOR-SCHEME-3-ACCENTS](https://user-images.githubusercontent.com/49079412/95550134-3f46b700-09bd-11eb-96a7-5d2957437c7a.png)
![BOW-AND-ARROW-COLOR-SCHEME-ROUGH-FIRST](https://user-images.githubusercontent.com/49079412/95550136-3fdf4d80-09bd-11eb-8f57-25d4db3687c5.png)
